language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_29d39fff9511_key -iv $encrypted_29d39fff9511_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
